### ISSUE TITLE
第6课运行 main.py 的时候报错

### ISSUE THREAD

**Issue by syauwjl** [51bitquant/howtrader#36]
您好，我在class 6 运行main.py 的时候报错，麻烦帮着看看，谢谢。
(mytrader) PS E:\07个人材料\量化学习\19bitquant\VNPY数字货币量化交易从零到实盘\course_codes-main\class_06> python main.py
Traceback (most recent call last):
  File "F:\anaconda\envs\mytrader\lib\site-packages\aiohttp\client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\07个人材料\量化学习\19bitquant\VNPY数字货币量化交易从零到实盘\course_codes-main\class_06\main.py", line 7, in <module>
    from howtrader.gateway.binance import BinanceUsdtGateway, BinanceSpotGateway, BinanceInverseGateway
  File "F:\anaconda\envs\mytrader\lib\site-packages\howtrader\gateway\binance\__init__.py", line 1, in <module>
    from .binance_spot_gateway import BinanceSpotGateway
  File "F:\anaconda\envs\mytrader\lib\site-packages\howtrader\gateway\binance\binance_spot_gateway.py", line 41, in <module>     
    from howtrader.api.rest import RestClient, Request, Response
  File "F:\anaconda\envs\mytrader\lib\site-packages\howtrader\api\rest\__init__.py", line 1, in <module>
    from .rest_client import RestClient, Request, Response
  File "F:\anaconda\envs\mytrader\lib\site-packages\howtrader\api\rest\rest_client.py", line 19, in <module>
    from aiohttp import ClientSession, ClientResponse
  File "F:\anaconda\envs\mytrader\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "F:\anaconda\envs\mytrader\lib\site-packages\aiohttp\client.py", line 59, in <module>
    from .client_reqrep import (
  File "F:\anaconda\envs\mytrader\lib\site-packages\aiohttp\client_reqrep.py", line 72, in <module>
    import charset_normalizer as chardet  # type: ignore[no-redef]
  File "F:\anaconda\envs\mytrader\lib\site-packages\charset_normalizer\__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "F:\anaconda\envs\mytrader\lib\site-packages\charset_normalizer\api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by syauwjl** [comment]
噢噢噢，缺了包。已经解决了。
