### ISSUE TITLE
回测时遇到了问题，提示如下

### ISSUE THREAD

**Issue by Praying** [51bitquant/howtrader#9]
17:30:06	策略初始化完成
17:30:06	策略回测失败，触发异常：
Traceback (most recent call last):
  File "D:\Anaconda\envs\vnpy\lib\site-packages\howtrader\app\cta_backtester\engine.py", line 161, in run_backtesting
    engine.run_backtesting()
  File "D:\Anaconda\envs\vnpy\lib\site-packages\howtrader\app\cta_strategy\backtesting.py", line 295, in run_backtesting
    self.strategy.on_start()
  File "D:\Anaconda\envs\vnpy\lib\site-packages\howtrader\app\cta_strategy\strategies\spot_simple_grid_strategy.py", line 64, in on_start
    self.cta_engine.event_engine.register(EVENT_TIMER, self.process_timer_event)
AttributeError: 'BacktestingEngine' object has no attribute 'event_engine'

**Comment by 51bitquant** [comment]
你用到是实盘的代码了，实盘的代码里面咩有回测引擎。内置网格代码没有支持回测功能

**Comment by Praying** [comment]
哦哦，howtrader啥时候可以支持一下Okex的接口，虽然官方的vnpy有，但是每次都要登录，还挺麻烦的。。。

**Comment by 51bitquant** [comment]
在增加okex等交易所接口，还在开发中。
